### ISSUE TITLE
All vehicle information stopped updating

### ISSUE THREAD

**Issue by rstremke** [G-Two/homeassistant-subaru#102]
I've been using the HACS MySubaru Custom Integration for a couple months now. It's always worked flawlessly. Then 2023-11-10 at 10am, all the data (odometer, fuel mileage, tire pressure, etc.) stopped updating for both my Outback and my wife's Outback. I can see the data if I log in to the MySubaru app or website, so it does not appear to be an issue with the vehicles. I restarted Home Assistant, checked for Integration updates, and even removed and re-configured my MySubaru account. Nothing has had any effect. Pressing the Poll Vehicle button seems to complete successfully (no errors) but does not refresh any of the entities. 

All the entities (except remote start, which still works) show as unavailable. When I tried to press the Refresh button (button.ryans_outback_refresh), I got the following error: Failed to call service button/press. time data 2023-11-11T04:21:39.000+0000' does not match format '%Y-%m-%dT%H:%M:%S%z

Unsure if that's related to my current issue. 

I really enjoy this Integration, and has been quite useful in my home. Any assistance is appreciated. Thanks.

**Comment by G-Two** [comment]
This seems to be the same as #101. Please confirm that you are running [0.7.12](https://github.com/G-Two/homeassistant-subaru/releases/tag/v0.7.12)? If so, please paste the integration and device diagnostics output.

**Comment by rstremke** [comment]
My apologies, I should have looked at the closed issues first. Thanks for your quick response and fix. Downloading 0.7.12 worked! I was expecting to see it as an available update, but I should have checked the custom repository. Now I know :)

This is resolved. Thanks, again!
