### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by 715Steve** [G-Two/homeassistant-subaru#108]
This stopped working in some prior update of the HA Core.
All entities were offline so I removed the module and re-added but am unable to authenticate now.

I installed the HA cloud Subaru module without issue, this seems to be limited to the HACS version.

I don't have logs as I am running the internal module now although it has less features.

**Comment by G-Two** [comment]
Subaru (HACS) 0.7.12 works with HA Core 2024.1.5

If you're using versions other than those, you'll need to be more specific. There's nothing I can do to help without logs, diagnostics output, or any other information other than it stopped working for you.

The internal HA Core Subaru uses the exact same [subarulink](https://github.com/G-Two/subarulink) authentication functions as the HACS version, so the problem may have just been a temporary outage on the Subaru side. Or your version of Subaru (HACS) might be out of date.

**Comment by 715Steve** [comment]
No bug.
