### ISSUE TITLE
Doors lock or unlocked state unknown

### ISSUE THREAD

**Issue by ComputerWarlock** [G-Two/homeassistant-subaru#114]
Don't know if I am missing something or not but the door lock state is unknown.
I havn't been able to figure out if I need to do some custom settings in a YAML or not.

If I click Lock or Unlock button in the integration it actually does lock and unlock all the doors, which is the desired thing, I can confirm this with emails from Subaru and checking the car in person. 
All the other sensors seem to be working, windows closed, doors closed, fuel level, just the door lock state. I can even remote start the car.

**Comment by ComputerWarlock** [comment]
If anyone has or sees this and isn't sure like me I was reading the source code and there is a comment I see that this is the current thing and there isn't a way to return the known state of the locks, so they will always show unknown.

**Comment by G-Two** [comment]
I added a note to the README.md that mentions this now, so others don't have to dig through the source to find out.
