### ISSUE TITLE
2021.8 Changed VOLT const

### ISSUE THREAD

**Issue by stboch** [G-Two/homeassistant-subaru#15]
with the new energy features in version 2021.8 VOLT has been renamed to ELECTRIC_POTENTIAL_VOLT

**Comment by G-Two** [comment]
Thanks for catching that. I've staged the change in v0.5.0 and will release once I test on my setup. I'll setup a nightly pytest run against the latest home assistant release to try and catch things like this.

**Comment by stboch** [comment]
Hey can you create a pre-release for v0.5.0 that way I can have it update via hacs nice an easy as a beta test ;)

**Comment by G-Two** [comment]
Done

**Comment by stboch** [comment]
Ok looks good. Opened new issue for additional 0.5.0
