### ISSUE TITLE
Dismiss persistent notifications

### ISSUE THREAD

**Issue by ACiDGRiM** [G-Two/homeassistant-subaru#20]
I personally would prefer to not have a notification every time I call a Subaru service. I've looked though your code and can only tell that the notification ID is assigned the DOMAIN variable. I'm not a developer and can't identify where the value of DOMAIN is pulled from to call persistent_notification.dismiss

Can you please give me some information or if this is a possible use case for this integration, allow the notifications to be disabled unless there's an error message.

All said, this is by far the most functional integration in all of HA. Thank you.

**Comment by G-Two** [comment]
@ACiDGRiM `DOMAIN` is imported from [const.py](https://github.com/G-Two/homeassistant-subaru/blob/e282f84800b424cf4e72a90a528cbaf54151f68a/custom_components/subaru/const.py#L3) and has the value `"subaru"`.  I think your use case makes sense, in the next release I'll add an option to disable notifications of successful remote commands. Thanks for the feedback!
