### ISSUE TITLE
New profiles feature

### ISSUE THREAD

**Issue by ACiDGRiM** [G-Two/homeassistant-subaru#24]
Will there be any plans to be able to call remote start with a user preset? This appears to be a new feature in starlink.

**Comment by tango2590** [comment]
I second this. Would be nice to choose which preset to remote start with instead of using the generic "last used settings".

**Comment by ACiDGRiM** [comment]
This should be linked to the upstream library, I've opened an issue there
Duplicate of https://github.com/G-Two/subarulink/issues/46

**Comment by ACiDGRiM** [comment]
@tango2590 This is resolved with the latest release. see release notes.
