### ISSUE TITLE
Start service climate settings

### ISSUE THREAD

**Issue by jonslilbro** [G-Two/homeassistant-subaru#32]
No matter what I do(manually starting from the Subaru app from a preset or manually choosing climate settings), everytime I start from HA it always starts with my climate set to 65. In the summer, this wasn't really an issue, but now that it's cold out I really want the system to heat up my car and start melting snow. How can I change the default climate setting that the integration starts using?

**Comment by stboch** [comment]
I think the issue is the way the app has moved away from the old climate settings which is what is pulled and used by the HA start command. I was looking into the new settings in another issue, will recommend using that to keep track of this.

**Comment by stboch** [comment]
@jonslilbro This new update should resolve your issue please update and test. This will now use climate presets
