### ISSUE TITLE
Button Press Remote Start Fails

### ISSUE THREAD

**Issue by reichley** [G-Two/homeassistant-subaru#41]
Greetings and thank you for this integration. Being able to interface/control my vehicles via home assistant is wonderful. I recently upgraded to 0.6 and attempted to use one of the newly-created button entities, specifically remote_start. Upon pressing it HA throws the following error: 

``
Failed to call service button.press. Service
remote_start failed for Forester: Climate preset 'None' does not exist 
``

I’m not sure there’s a way to add service data to a button entity generated by an integration. What do you think about assigning the default preset of 'Auto' to the entity upon creation?

**Comment by ACiDGRiM** [comment]
`Climate preset 'None' does not exist`

The answer is in the Error. you need to specify a preset in the select.2019_ascent_limited_climate_preset entity.
You create presets in the mobile app or website.

**Comment by reichley** [comment]
Ah, yes! I definitely must’ve overlooked that bit. I’ll set them and restart HA to see if they persist. Thanks!

**Comment by G-Two** [comment]
@reichley I thought about assigning a default preset, but not all cars have an 'Auto' preset. I didn't want to make a default choice for the user on 'Full Cool' or 'Full Heat' and cause an unexpected surprise. Once you select a preset in HA, it should persist. It will revert back to 'None' if the selected preset is ever deleted.

**Comment by reichley** [comment]
Thanks @G-Two! Keep up the great work.
