### ISSUE TITLE
Extend integration settings to poll subaru starlink every X minutes

### ISSUE THREAD

**Issue by ACiDGRiM** [G-Two/homeassistant-subaru#49]
I think that ensuring that what ever is in starlink is up to date regularly can be helpful. The 2 hour locate may be a little heavy when it's just necessary to sync homeassistant with starlink.

**Comment by G-Two** [comment]
The integration already polls the subaru for data every 5 minutes. It is currently not a configurable setting. If you set your logs to debug, you'll see activity occur every 5 minutes as part of the default/built-in behavior of the integration. If this interval suits your needs, then there is no need to have an automation call the button press. The integration's built-in 5 minute polling also doesn't leave persistent notifications.

**Comment by ACiDGRiM** [comment]
Thanks for the info and foresight.
