### ISSUE TITLE
Suppress non-API errors such as "ignition on"

### ISSUE THREAD

**Issue by ACiDGRiM** [G-Two/homeassistant-subaru#53]
Someone stole a gear bag out of my car on two separate occasions, once while I was literally 20ft away in my house packing anothrer dufflebag and another time while I was asleep and forgot to lock my doors. So this addon has suddenly become incredibly important to me.

Cops are useless, so the video camera I have recording my car almost became a waste of money, however I rediscovered the flash lights and honk horn buttons. Now, when there's any motion detected around my car, this home assistant automation will lock my doors, just in case and start the lights flashing and horn honking. This works so well, fortunately it's only scared away a cat so far at 3am, but one issue I have is with the errors when I'm loading up into the car or driving in.

My home assistant persistent notifications are full of failure notifications because the ignition is on when the command is received. I do check the device tracker location for the vehicles location and if ignition sensor is on, but that isn't always accurate. I still want to have errors logged if the API fails, however I run all my automation in node red, so I can detect errors and act on them mid flow.

It would be nice to have the notification setting just log all errors to the home assistant logs and disable persistent notifications, or filter out ignition on responses.

I seriously can't thank you enough for developing this, at first it was just convenient to warm up the car in the morning, but it's proving to be the single most valuable software I've ever used.

V0.6.2

**Comment by G-Two** [comment]
Sorry to hear about the thefts, but I'm glad at least this integration is proving to be useful for hopefully preventing another. I added an option to disable all persistent notifications (errors will still be logged). Give [v0.6.3rc0](https://github.com/G-Two/homeassistant-subaru/tree/v0.6.3rc0) a try and let me know if it works for you.
