### ISSUE TITLE
Cannot lock car via Automations (Missing service)

### ISSUE THREAD

**Issue by TheCre8r** [G-Two/homeassistant-subaru#62]
I see `subaru.unlock_specific_door` but I do not see any sort of `subaru.lock` in the services for Automations
![image](https://user-images.githubusercontent.com/6027150/202879560-b4f12ad0-c4f8-4f98-a61f-b5f91ef5f63d.png)

**Comment by G-Two** [comment]
You can just use `lock.lock` and `lock.unlock` then specify your Subaru device as the target.

**Comment by TheCre8r** [comment]
Thank you! A little too obvious.
