### ISSUE TITLE
2023 Outback only has odometer sensor

### ISSUE THREAD

**Issue by Mmangg** [G-Two/homeassistant-subaru#69]
Currently I only have the odometer sensor after loading this integration into HA via HACS. I've attached a copy of the diagnostics showing I am getting additional data back.
[subaru-c6aa80ce45540ab4e50ba7f9e0f986c6-2023 Outback Touring-c778143cf4f458573052e7b05e4a6880.json.txt](https://github.com/G-Two/homeassistant-subaru/files/10272659/subaru-c6aa80ce45540ab4e50ba7f9e0f986c6-2023.Outback.Touring-c778143cf4f458573052e7b05e4a6880.json.txt)

**Comment by G-Two** [comment]
Oh cool, you have a g3 vehicle! I've been wanting to get some data from one in order to support it. Thanks, I'll try to push out an update soon that will get the rest of the sensors working for you, along with the additional new ones for g3 (fuel level remaining, sunroof tilt/open indicator, etc.)

**Comment by RickG81** [comment]
I thought it was just me having the problem and have been driving myself crazy trying to figure it out!  I have a '23 Legacy.  

@G-Two I've attached a screenshot of the error logs if it helps any.  The error is:  "replace() argument 2 must be str, not None" whenever I try to execute any command other than location or odometer.  

![logs](https://user-images.githubusercontent.com/107275728/209404369-c7a795ca-be97-4d10-92e4-55e4b12410ee.png)


Thank you for your hard work on this!

**Comment by G-Two** [comment]
Please give v0.7.2rc0 a try and let me know if it resolves issues with 2023 model year vehicles. Thanks!

**Comment by RickG81** [comment]
Thanks for the quick response.  Not sure if I'm doing something wrong or not, but now I'm getting a 404 error.  I tried to delete and re-add the integration but no go.  It authenticates with Subaru properly, but the commands don't seem to work.  Log attached.  Please let me know if there is any other information I can provide to help.  

[log.txt](https://github.com/G-Two/homeassistant-subaru/files/10304947/log.txt)

**Comment by G-Two** [comment]
You're not doing anything incorrect. Thanks for the logs. I see another change I need to make to work with g3. I'll let you know when I push a new revision.

**Comment by RickG81** [comment]
Thank you.  If there is any more details you need, I'm happy to provide anything I can.

**Comment by G-Two** [comment]
v0.7.2rc1 should hopefully fix the 404 issue you encountered and give you full functionality.

**Comment by RickG81** [comment]
I'm now getting a 500 error when trying to issue a command (in this case, lock).  Logs attached.  Thank you.

[500 error.txt](https://github.com/G-Two/homeassistant-subaru/files/10308765/500.error.txt)

**Comment by G-Two** [comment]
I'm an idiot and made a really dumb logic error. Thanks for the logs, I'll fix it soon.

**Comment by G-Two** [comment]
v0.7.2rc2 should fix the 500 error for 2023 vehicles.

**Comment by RickG81** [comment]
That seems to have done it, thanks!  I haven't tested out everything yet but quickly did an unlock/lock and can see my tire pressure and mpg averages showing up along with location and odometer.   Will test out everything more thoroughly over the next few days.

**Comment by RickG81** [comment]
Just wanted to follow up here, I have tested all the basic functions and everything seems to be working great so far.  Thank you!
