### ISSUE TITLE
Remote start from Lovelace yaml producing error

### ISSUE THREAD

**Issue by dredjohn21** [G-Two/homeassistant-subaru#72]
I’m getting the following error when trying to remote start from the Lovelace ui:
‘remote_start command failed for Subaru Ascent: Climate preset 'None' does not exist‘

I built the UI per the YAML example.

I’m assuming something else is needed?  I see references to climate in the separate service section of the readme- so probably user error on my part (apologies!)

**Comment by G-Two** [comment]
You'll need to make a climate preset selection first (using the `select.<vehicle_name>_climate_preset entity`) before attempting remote start. See https://github.com/G-Two/homeassistant-subaru/issues/41

**Comment by G-Two** [comment]
Closing as stale / nothing to fix.
