### ISSUE TITLE
Unable to select an option from the drop down for climate preset

### ISSUE THREAD

**Issue by analogpotato** [G-Two/homeassistant-subaru#77]
Sorry if this is a newbie question, but I just setup this via HACS with a vanilla install and it's not giving me any presets for climate options. I checked out the other issues and #41 suggests setting a custom (non stock) preset in the mobile app which I did. Is there a way to refresh these options? I'm just using the GUI at the moment, I am very new to HA and this was my first time setting up a HACS extension.

**Comment by analogpotato** [comment]
![Screenshot 2023-02-07 at 11 04 07 PM](https://user-images.githubusercontent.com/42280875/217458122-4ca173be-ad21-4d87-be18-2f2503b58c19.png)

This is what it looks like when I click on the default climate preset selection

**Comment by G-Two** [comment]
Same issue as #78 (fixed in 0.7.5rc0)
