### ISSUE TITLE
PIN Failing Even though it's correct

### ISSUE THREAD

**Issue by lordexorr** [G-Two/homeassistant-subaru#8]
I'm having an issue. I installed the integration and linked it to my Starlink account but then realized my subscription didn't include all sensors available so I removed the integration completely (restarted after, etc) and upgraded my Starlink subscription to include the rest of the sensors. Now when I try to install the integration again it gets to the "PIN" field and whenever I enter it, it states my "PIN is incorrect" even though I know it's not and it worked before.

Is there something cached on HA I need to clean up, any idea what's happening here?

Thanks!

**Comment by lordexorr** [comment]
I think I figured this out. When you have multiple cars linked to your Starlink account Subaru has a DIFFERENT PIN for each one. What happened was one of the cars had a different PIN than the other car which Subaru is fine with, but the integration must need to confirm the PIN for both vehicles during setup and if they don't match, it causes an issue.

In short; I updated the PIN for both cars to the same PIN and then was able to get Home Assistant re-added.

If you want to add to your install guide, when logged into MySubaru you have to change the car your managing, then go to security, and update PIN, then change to the other car, and update PIN there too.

**Comment by G-Two** [comment]
Yeah, the PIN verifier is hacky and just uses the first vehicle to test and saves that for all vehicles on the account. I've been meaning to support different PINs at some point, but it's super low priority. Thanks for the feedback, I'll update the documentation and maybe put a note in the UI dialog box.
