### ISSUE TITLE
Device tracker for subaru entity no longer available.

### ISSUE THREAD

**Issue by DerekF35** [G-Two/homeassistant-subaru#90]
I haven't been able to pin down if this is related to the 2023.07 update or not, but yesterday my device_tracker entity for my 2019 Subaru Forrester went unavailable.  I think the Lat and Lon are appearing in the diagnostics, but they are redeacted.

[config_entry-subaru-362393d662e05f9cc7a1ec28b5ac4371.json.txt](https://github.com/G-Two/homeassistant-subaru/files/11973703/config_entry-subaru-362393d662e05f9cc7a1ec28b5ac4371.json.txt)

`Logger: homeassistant.components.device_tracker
Source: helpers/entity.py:459
Integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 9:14:33 PM (2 occurrences)
Last logged: 9:14:33 PM

Error adding entities for domain device_tracker with platform subaru
Error while setting up subaru platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 680, in _async_add_entity
    f"{device_name} {entity.suggested_object_id}"
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in suggested_object_id
    if self.__class__.name.fget is Entity.name.fget and self.platform:  # type: ignore[attr-defined]
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'fget'`

**Comment by zanix** [comment]
It might be related to this change
https://developers.home-assistant.io/blog/2023/06/28/entity-name-changes/

**Comment by zanix** [comment]
Adding a name property definition to `device_tracker.py` seems to work

Below:

```python
    def __init__(self, vehicle_info: dict, coordinator: DataUpdateCoordinator) -> None:
        """Initialize the device tracker."""
        super().__init__(coordinator)
        self.vin = vehicle_info[VEHICLE_VIN]
        self._attr_device_info = get_device_info(vehicle_info)
        self._attr_unique_id = f"{self.vin}_location"
```

Add

```yaml
    @property
    def name(self):
        return "Location"
```

This seems to bring back the device tracker and seems to work correctly.
I would make a PR, but I'm not 100% sure if this is the correct fix or not.

**Comment by G-Two** [comment]
@zanix Thanks for narrowing down the cause. I'll release an update tonight that fixes the issue.

**Comment by G-Two** [comment]
[v0.7.9](https://github.com/G-Two/homeassistant-subaru/releases/tag/v0.7.9) should fix this issue.

**Comment by DerekF35** [comment]
Confirmed the fix works.  Thanks for a quick fix.
