### ISSUE TITLE
Vehicle Location unavaiable.

### ISSUE THREAD

**Issue by BobRathke** [G-Two/homeassistant-subaru#92]
After upgrading to HA 2022.7.1 I am no longer getting a location for my 2016 XTrek. All other sensors & function works as expected.

Here is the only log entry I located.

Logger: homeassistant.components.device_tracker
Source: helpers/entity.py:459
Integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: July 9, 2023 at 9:13:56 AM (4 occurrences)
Last logged: 6:23:49 AM

Error adding entities for domain device_tracker with platform subaru
Error while setting up subaru platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 680, in _async_add_entity
    f"{device_name} {entity.suggested_object_id}"
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in suggested_object_id
    if self.__class__.name.fget is Entity.name.fget and self.platform:  # type: ignore[attr-defined]
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'fget'

**Comment by DerekF35** [comment]
Are you using the latest version?
 https://github.com/G-Two/homeassistant-subaru/releases/tag/v0.7.9

A fix for this issue was just released that may fix your problem.

https://github.com/G-Two/homeassistant-subaru/issues/90
