### ISSUE TITLE
Sunroof and window entities are missing from 2023 Subaru Ascent Touring

### ISSUE THREAD

**Issue by dshokouhi** [G-Two/homeassistant-subaru#93]
Looking at the diagnostics file I can see that sunroof should be supported as my vehicle reports the correct feature `PANPM-DG2G` and state `"windowSunroofStatus": "CLOSE",`

regarding power windows I do see the states in the diagnostics file however I do not see the defined const, maybe it changed in my car?

```
"windowFrontLeftStatus": "CLOSE",
"windowFrontRightStatus": "CLOSE",
"windowRearLeftStatus": "CLOSE",
"windowRearRightStatus": "CLOSE",
```

would love to get support for these if possible!

[subaru-6a3db59af40a32d6f6a7cf621c5d6d95-2023 Ascent Touring-3caf25b92179e46d4fe74d045a0d2b66.json.txt](https://github.com/G-Two/homeassistant-subaru/files/12045532/subaru-6a3db59af40a32d6f6a7cf621c5d6d95-2023.Ascent.Touring-3caf25b92179e46d4fe74d045a0d2b66.json.txt)

**Comment by G-Two** [comment]
I think I see the problem. I made the assumption that power sunroof (PANPM-DG2G) vehicles would also have the power windows feature (PWAAADWWAP). If the vehicle doesn't report having PWAAADWWAP, then windows and sunroom status (incorrectly) don't get added. I'll put out a test release soon that should fix it.

**Comment by dshokouhi** [comment]
so if my car doesnt report the power windows key it doesnt support it? I guess the API just returns bad data in that case? Personally  havent tested the response to see if its correct, saw the data and assumed it would work 😅

**Comment by G-Two** [comment]
Your car should support it as it seems (according to your diagnostics output) PANPM-DG2G also has all the features of PWAAADWWAP. I just need to update [subaurlink](https://github.com/G-Two/subarulink) to parse all the data expected from PWAAADWWAP for all PANPM-DG2G vehicles.

**Comment by G-Two** [comment]
Try the latest release 0.7.10 and let me know if your windows and sunroof entities show up properly.

**Comment by dshokouhi** [comment]
yup windows and sunroof entities are showing up now, thank you!!!

**Comment by gavinhogan** [comment]
Oh wow.... I did not know this was even possible with the Ascent until I saw this in the release notes this morning. 

Sadly, I think it is not working in my specific case - Ascent 2019. I just tested with my car and while the values do not show up in the HA integration... I do see the correct values for windows being open in the diagnostic. The sunroof does not seem to report any value (it is currently open but the diagnostic shows it as UNKNOWN).

### Features
`     "vehicle_features": [
        "ABS_MIL",
        "ACCS",
        "AHBL_MIL",
        "ATF_MIL",
        "AWD_MIL",
        "BSD",
        "BSDRCT_MIL",
        "CEL_MIL",
        "EBD_MIL",
        "EOL_MIL",
        "EPAS_MIL",
        "EPB_MIL",
        "ESS_MIL",
        "EYESIGHT",
        "NAV_TOMTOM",
        "OPL_MIL",
        "RAB_MIL",
        "RCC",
        "REARBRK",
        "RES",
        "RESCC",
        "RHSF",
        "RHVAC",
        "RPOIA",
        "SRS_MIL",
        "TEL_MIL",
        "TIF_33",
        "TIR_33",
        "TPMS_MIL",
        "VDC_MIL",
        "WASH_MIL",
        "g2"
      ],`

### rawData.condition
` 
   "windowFrontLeftStatus": "OPEN",
    "windowFrontRightStatus": "OPEN",
    "windowRearLeftStatus": "CLOSE",
    "windowRearRightStatus": "CLOSE",
    "windowSunroofStatus": "UNKNOWN",
    `
### rawData.vehicleStatus
    ` "windowFrontLeftStatus": "VENTED",
          "windowFrontRightStatus": "VENTED",
          "windowRearLeftStatus": "CLOSE",
          "windowRearRightStatus": "CLOSE",
          "windowSunroofStatus": "UNKNOWN",`


[subaru-eebf19302bc5d0c9c01ebdb8fedb7f51-4S4WMAPD5K3476397-28ee56cb4710854d89e6b0d878f4d53c.json(1).txt](https://github.com/G-Two/homeassistant-subaru/files/12139778/subaru-eebf19302bc5d0c9c01ebdb8fedb7f51-4S4WMAPD5K3476397-28ee56cb4710854d89e6b0d878f4d53c.json.1.txt)

**Comment by G-Two** [comment]
g2 vehicles seem to be inconsistent as to which models properly report window status. My 2019 Crosstrek always reports front windows as "VENTED", regardless of their actual state (rear and sunroof are always "UNKNOWN"). If your 2019 Ascent is reliably reporting front and rear window state in rawData.condition, then we should be able to report it to home assistant. I just need a way to reliably know that the data is valid.

Does the MySubaru app report your window status correctly? If so, I can look through the app and figure out how it is determining the feature exists and do the same within subarulink.
