### ISSUE TITLE
Unable to add add-on via Home Assistant OS

### ISSUE THREAD

**Issue by CodyEngel** [G-Two/homeassistant-subaru#97]
I'm running Home Assistant OS as a VM in Proxmox and have been unable to add this integration. When I copy and paste the repository url into "manage add-on repositories" I get the following error message: "https://github.com/G-Two/homeassistant-subaru is not a valid add-on repository".

Is this the expected behavior?

**Comment by stboch** [comment]
This is a HACS integraton not an addon.

**Comment by G-Two** [comment]
Closing as stale / nothing to fix.
