### ISSUE TITLE
Lock Command Fails After Recent Update

### ISSUE THREAD

**Issue by clearwave1** [G-Two/homeassistant-subaru#98]
The lock command has been failing recently with the following error:

lock command failed for JF2GTHSCXMH285553: HTTP 500: {"httpCode":500,"errorCode":"error","errorMessage":"java.lang.NullPointerException - null"} RequestInfo(url=URL('https://mobileapi.ca.prod.subarucs.com/g2v27/service/g2/remoteService/status.json?serviceRequestId=JF2GTHSCXMH285553_1696350839345_20_@NGTP'), method='GET', headers=<CIMultiDictProxy('Host': 'mobileapi.ca.prod.subarucs.com', 'User-Agent': 'Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/QSR1.191030.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.185 Mobile Safari/537.36', 'Origin': 'file://', 'X-Requested-With': 'ca.subaru.telematics.remote', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Cookie': 'JSESSIONID=88E16CA6EC274E845CA877782B07A3F6; X-Oracle-BMC-LBS-Route=edfba615976e065ee5f0d8b86c4407c36046567791298f75028beb1a771f42d57a0731b7bb9e0c7b')>, real_url=URL('https://mobileapi.ca.prod.subarucs.com/g2v27/service/g2/remoteService/status.json?serviceRequestId=JF2GTHSCXMH285553_1696350839345_20_@NGTP'))

I'm not sure if this is caused by my latest Home Assistant update or whether Subaru changed something on their side.

**Comment by G-Two** [comment]
Is this failure still occurring? I'm not able to duplicate.

**Comment by clearwave1** [comment]
I did some testing tonight and it is working now.

I'm assuming this was a temporary issue with their servers. I'll report if it happens again.

**Comment by clearwave1** [comment]
This happened again about 1 hour ago. I'll reopen this report if it starts to happen regularly again.
